// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqoEFRl5dc-0C5zBN8H3bmCauJ6lStViM',
    appId: '1:64959225182:web:62877e882db248ad9bc3cf',
    messagingSenderId: '64959225182',
    projectId: 'nomad-coder-moodtracker',
    authDomain: 'nomad-coder-moodtracker.firebaseapp.com',
    storageBucket: 'nomad-coder-moodtracker.appspot.com',
    measurementId: 'G-84QS8R91H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyxuJs2dBQT7F12f4GDdE5iC6N4yGHPCw',
    appId: '1:64959225182:android:3db19b4cc9072e989bc3cf',
    messagingSenderId: '64959225182',
    projectId: 'nomad-coder-moodtracker',
    storageBucket: 'nomad-coder-moodtracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25VOv8eyjyK5m7AJfjrgNa_ySvUlYg_o',
    appId: '1:64959225182:ios:55628119a40f33409bc3cf',
    messagingSenderId: '64959225182',
    projectId: 'nomad-coder-moodtracker',
    storageBucket: 'nomad-coder-moodtracker.appspot.com',
    iosBundleId: 'com.example.flutterSeniorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqoEFRl5dc-0C5zBN8H3bmCauJ6lStViM',
    appId: '1:64959225182:web:42cecc92f7e7f0d29bc3cf',
    messagingSenderId: '64959225182',
    projectId: 'nomad-coder-moodtracker',
    authDomain: 'nomad-coder-moodtracker.firebaseapp.com',
    storageBucket: 'nomad-coder-moodtracker.appspot.com',
    measurementId: 'G-X88EP4N0HR',
  );

}